version: '3.4'

services:
  backendCarShop:
    image: ipzdocker
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - back
    ports:
    - "8080:80"
    depends_on:
    - carShopDB
    environment:
        ConnectionStrings__DefaultConnection: "Encrypt=false;server=carShopDB;database=carShopDB;User=sa;password=Qwerty123!"
        
  carShopDB:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
    - "1433:1433"
    networks:
    - back
    environment:
        SA_PASSWORD: "Qwerty123!"
        ACCEPT_EULA: "Y"

networks:
  back:
    driver: bridge