FROM lab01_1brshp:latest
# Create a volume to persist the Nginx HTML directory
VOLUME /usr/share/nginx/html
# Copy your index.html file to the Nginx document root
COPY /lab01/index.html /usr/share/nginx/html/index.html